name: 'whitesource-ua-azdo-c'

trigger:
- OpenSSL_1_1_1h

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: CmdLine@2
  displayName: 'WhiteSource Scan'
  inputs:
    script: |
      echo Downloading WhiteSource Unified Agent
      curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
      export WS_APIKEY=$(WS_ApiKey)
      export WS_WSS_URL=$(WS_WssUrl)
      export WS_RESOLVEALLDEPENDENCIES=false
      echo WhiteSource Scan
      java -jar wss-unified-agent.jar -product "$(Build.Repository.Name)" -project "$(Build.DefinitionName)"
